### ISSUE TITLE
`__getitem__()` for Record sends back its argument

### ISSUE THREAD

**Issue by vincentbernat** [digitalocean/pynetbox#281] opened 2020-08-11 11:18 UTC
Hey!

The code for `__getitem__()` in `response.py` is:

```python
    def __getitem__(self, item):
        return item
```

This is quite confusing if you happen to use the dict notation instead of the attribute notation. I would suggest to either support the dict notation properly (not tested and `__setitem__()` should be implemented too):

```diff
diff --git a/pynetbox/core/response.py b/pynetbox/core/response.py
index 49d9dc57cdeb..f2c8aed4f84a 100644
--- a/pynetbox/core/response.py
+++ b/pynetbox/core/response.py
@@ -186,14 +186,11 @@ class Record(object):
         In order to prevent non-explicit behavior,`k='keys'` is
         excluded because casting to dict() calls this attr.
         """
-        if self.url:
-            if self.has_details is False and k != "keys":
-                if self.full_details():
-                    ret = getattr(self, k, None)
-                    if ret or hasattr(self, k):
-                        return ret
-
-        raise AttributeError('object has no attribute "{}"'.format(k))
+        if k != "keys":
+            try:
+                return self[k]
+            except KeyError:
+                raise AttributeError('object has no attribute "{}"'.format(k))
 
     def __iter__(self):
         for i in dict(self._init_cache):
@@ -207,8 +204,15 @@ class Record(object):
             else:
                 yield i, cur_attr
 
-    def __getitem__(self, item):
-        return item
+    def __getitem__(self, k):
+        if self.url:
+            if self.has_details is False:
+                if self.full_details():
+                    ret = getattr(self, k, None)
+                    if ret:
+                        return ret
+
+        raise KeyError('object has not key "{}"'.format(k))
 
     def __str__(self):
         return getattr(self, "name", None) or getattr(self, "label", None) or ""
```

Or to remove this `__getitem()__` to not let the user retrieve obviously incorrect results.

I was being started on the first solution, but maybe I am missing something?

**Comment by zachmoody** [comment] 2020-08-11 18:19
Interesting thought, just to give some background (and going completely on memory) the whole point in implementing it was so that users could easily cast objects to dicts to help in debugging. It was never really intended to be a fully featured interface in parallel with attributes. Not saying it couldn't be, but hasn't really been an issue before.

**Comment by vincentbernat** [comment] 2020-08-11 21:36
It's mostly when you want to access an attribute whose name is in a variable. Using `record[attribute]` is more natural than `getattr(record, attribute)`. Maybe a very first step would be to remove the `__getitem__()` accessor since it's error prone. I have fallen twice in this trap in two months. I was quite surprised nobody reported the issue yet.

**Comment by zachmoody** [comment] 2020-08-11 21:52
Oh, wow, I see what you mean now :man_facepalming: . That's definitely not the intended behavior. Surprised there hasn't been a report already either. Think something like this would work?
```
def __getitem__(self, item):
    return getattr(self, item)
```
Along with some tests to make sure we don't mess it up again. Still not totally sure on implementing `__setitem__`, but getitem should be fixed for sure.

**Comment by vincentbernat** [comment] 2020-08-11 22:06
See my proposed patch to reverse stuff (but beware, not tested). Using `getattr()` in `__getitem__()` would make `record["full_details"]` returns something while it should trigger a `KeyError`. If you think we should fix `__getitem__()`, I can submit a proper PR.

**Comment by zachmoody** [comment] 2020-08-11 22:17
Ah ok, maybe condition on `callable()`? Not that there's anything wrong with your approach. I'm just terrified of messing with `__getattr__` :rofl: :sob:. A PR would be fantastic though, thank you.

**Comment by vincentbernat** [comment] 2020-08-12 04:42
In this case, `record["api"]` would return something too :)

**Closed** 2020-08-18 15:18 UTC
Labels: bug
