### ISSUE TITLE
The __version__ variable should be set on package installation.

### ISSUE THREAD

**Issue by ebusto** [digitalocean/pynetbox#58] opened 2018-05-21 23:35 UTC
As is, the library attempts to read a text file (`VERSION`) when it is loaded. If `pynetbox` is packaged in a ZIP archive, or synced using SaltStack's `saltutil.sync_modules`, this file is unavailable.

This change would make it easier to ship `pynetbox` as a dependency.

**Comment by zachmoody** [comment] 2018-05-22 14:52
Definitely not saying the way it's versioned is ideal, but why wouldn't that file be included in a zip? Totally open to better ideas around versioning though. Only made it this way because it was easier to remember when making changes. :laughing:

**Comment by ebusto** [comment] 2018-05-22 16:25
The `VERSION` file is included in the ZIP archive, but the `open` fails when using the module directly in the archive without first unzipping it.

Annoyingly, when SaltStack pushes out a custom execution module, it doesn't have a way to unzip if it is contained in an archive, and files not contained in an archive are skipped if they aren't actual Python source code.

**Comment by zachmoody** [comment] 2018-05-22 17:18
hrm, never used `_modules` to distribute python packages. Could you do something with the pip module or state to load it via pip? I'm guessing you don't have access to pypi from your salt stuff which is why you have to distribute an archive?

**Comment by ebusto** [comment] 2018-05-22 19:34
As bizarre as it may sound, we actually have thousands of hosts where installing the python-pip package requires jumping through some hoops to satisfy the security folks. :-/

**Comment by zachmoody** [comment] 2018-05-22 21:08
:scream: A pain in the ass for sure, but wouldn't be the most bizarre request I've heard from a security org  :smile:

I don't really know what best-practices are here. I think I had a look at a couple other packages and this was how they did it, but it's certainly not the only way. Thinking out loud, I wonder if setting `__version__` in `__init__.py` and reference that somehow in `setup.py`...oh, that's another thought too, you could do something like `python setup.py install` in salt to properly install it as a package after unarchiving it without needing pip.

**Comment by zachmoody** [comment] 2018-06-05 15:50
closing this out, you should be able to install without pip. I'm not sure that `_modules` was intended for use-cases like this, but if it is, and it's not syncing the `VERSION` file it might be worth getting with the Salt folks about it.

**Closed by zachmoody** 2018-06-05 15:50 UTC
