### ISSUE TITLE
the fonction .all() didn't work for nb.virtualization.virtual_machines. ?

### ISSUE THREAD

**Issue by victorh972** [digitalocean/pynetbox#283] opened 2020-08-18 05:38 UTC
i want to print all vm with their info with this nb.virtualization.virtual_machines.all() but that don't work because all() doesn't exist for this i supposed. so how can i do ?

**Comment by zachmoody** [comment] 2020-08-18 14:55
all() should exist on `virtual_machines`. Seems to work ok for me.

**Comment by victorh972** [comment] 2020-08-18 15:10
you write  nb.virtualization.virtual_machines.all() or somefing else ?

**Comment by zachmoody** [comment] 2020-08-18 15:17
Yeah, `nb.virtualization.virtual_machines.all()` if you want to pass filters you'd want to use the `.filter()` method, but I'm not sure what arguments the `virtual-machines` endpoint takes. You might want to have a look at the API docs and see what you can pass to it.

**Comment by victorh972** [comment] 2020-08-18 15:26
when i look the logs, i have this responses : ValueError: invalid literal for int() with base 10: 'AVAYA'
but my programme execute that : 

infoVM = nb.virtualization.virtual_machines.all()
print(infoVM)

i don't understand

**Comment by zachmoody** [comment] 2020-08-18 16:27
You could try adding
```import http
http.client.HTTPConnection.debuglevel = 1```
And see if you get any more details.

**Comment by victorh972** [comment] 2020-08-19 05:34
i try and i have this response :+1: send: b'GET /api/virtualization/virtual-machines/ HTTP/1.1\r\nHost: netbox.intranet.local\r\nAccept-Encoding: identity\r\nmycustomheader: test\r\naccept: application/json;\r\nauthorization: Token 1ffc8ed8429ae956201f9efa22ae7ee9e450de98\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Wed, 19 Aug 2020 05:33:26 GMT
header: Server: gunicorn/19.7.1
header: Content-Length: 40561
header: Vary: Accept,Cookie,Origin
header: Allow: GET, POST, HEAD, OPTIONS
header: API-Version: 2.4
header: X-Frame-Options: SAMEORIGIN
header: Content-Type: application/json
send: b'GET /api/virtualization/virtual-machines/?limit=259&offset=50 HTTP/1.1\r\nHost: netbox.intranet.local\r\nAccept-Encoding: identity\r\nmycustomheader: test\r\naccept: application/json;\r\nauthorization: 
Token 1ffc8ed8429ae956201f9efa22ae7ee9e450de98\r\n\r\n'
reply: 'HTTP/1.1 500 Internal Server Error\r\n'
header: Date: Wed, 19 Aug 2020 05:33:28 GMT
header: Server: gunicorn/19.7.1
header: API-Version: 2.4
header: Vary: Cookie,Origin
header: X-Frame-Options: SAMEORIGIN
header: Content-Type: text/html; charset=utf-8
header: Content-Length: 1773
header: Connection: close

**Comment by zachmoody** [comment] 2020-08-19 14:21
Tested against 2.7 here.

**Comment by victorh972** [comment] 2020-08-20 09:55
i don't arrived to upgrad netbox 2.4 on 2.8 version

**Comment by zachmoody** [comment] 2020-12-30 00:06
Nothing I can think of with pynetbox, could always just use the `requests` library directly. Will close this out for now since I can't reproduce.

**Closed by zachmoody** 2020-12-30 00:06 UTC
